title: "USNET Ltd"
email: usnetltd@outlook.com
timezone: UTC
baseurl: "/usnetltd.github.io"
permalink: "/:title/"
logo: 'assets/images/logo.png'
favicon: 'assets/images/favicon.ico'
author: usnet
paginate: 30
locale: en_gb
lang: en_gb
feed_items: 10
feed_update_period: daily
feed_update_frequency: 1
markdown: kramdown
kramdown:
  syntax_highlighter_opts:
    disable: true
sass:
  sass_dir: _sass
  style: :compressed
ganalytics: 

# Authors
authors:
  sal:
    name: usnet
    display_name: usnet
    avatar: 'assets/images/sal.png'
    email: usnetltd@outlook.com
    description: "Demo"

# Social
social:
  twitter: https://twitter.com/usnetltd

# Plugins
plugins: 
- jekyll-paginate
- jekyll-sitemap
- jekyll-feed
- jekyll-seo-tag
- jekyll-archives
